language: node_js
node_js:
  - "11.12.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - CI=false npm run build

after_success:
  - firebase deploy --only hosting --token "$FIREBASE_TOKEN"
