language: node_js
node_js:
  - "11.12.0"

branches:
  only:
    - master

before_script:
  - yarn add firebase-tools

script:
  - CI=false npm run build

after_success:
  - firebase login
  - y
  - firebase deploy --token "$FIREBASE_TOKEN"
